DefaultContentLanguage = "en"
title = "Bram Willemse"
theme = "bw-monochrome"

[pagination]
pagerSize = 16
path = "page"

# RSS, categories and tags disabled for an easy start
disableKinds = ["taxonomy", "term"]
enableInlineShortcodes = true

[markup.goldmark.renderer]
unsafe = true

# Add timeout settings to handle slow template rendering
timeout = "120s" # Increase timeout for Netlify builds