baseURL = "/"
DefaultContentLanguage = "en"
title = "Bram Willemse"
theme = "bw-monochrome"

[pagination]
pagerSize = 8
path = "page"

# RSS, categories and tags disabled for an easy start
disableKinds = ["RSS", "taxonomy", "term"]
enableInlineShortcodes = true

[markup.goldmark.renderer]
unsafe = true