[build]
  command = "yarn build:webpack && HUGO_TIMEOUT=120s HUGO_RESOURCEDIR=resources hugo --environment production --gc --minify"
[build.environment]
  NODE_VERSION = "23"
  YARN_VERSION = "1.22.22"
  HUGO_VERSION = "0.143.1"
