name = "Monochrome"
description = "A monochrome, black & white theme for my personal website."
homepage = "https://bramwillemse.nl"
tags = ["blog", "company"]

[author]
  name = "Bram Willemse"
  homepage = "Bram Willemse"
